name = "preferences-service"
type = "webpack"

workers_dev = false
webpack_config = "webpack.config.js"
compatibility_date = "2024-02-14"
node_compat = false

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "index.mjs"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[[d1_databases]]
binding = "user_prefs_database"
database_name = "preferences_database"
database_id = "dfd2f27f-7f6d-4fb5-806e-84e3d5b19dfb"

[vars]
CORS_DOMAINS = ".*.suncoast.systems,.*localhost.*"

